[editor]
color-modes = true

[editor.cursor-shape]
insert = "bar"

[keys.normal]
"{" = ["goto_prev_paragraph", "move_line_up", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
"0" = "goto_first_nonwhitespace"
"$" = "goto_line_end"
"F12" = ":tree-sitter-scopes"
"F11" = ":tree-sitter-highlight-name"

[keys.normal."]"]
"]" = ["goto_next_function", "flip_selections", "collapse_selection"]
"[" = ["goto_next_function", "collapse_selection"]

[keys.normal."["]
"]" = ["goto_prev_function", "flip_selections", "collapse_selection"]
"[" = ["goto_prev_function", "collapse_selection"]

[keys.insert]
"C-[" = "normal_mode"

[keys.select]
"C-[" = "normal_mode"
"0" = "goto_first_nonwhitespace"
"$" = "goto_line_end"
